name: TOC
channels:
  - defaults
dependencies:
  - beautifulsoup4=4.14.2=py314hca03da5_0
  - blinker=1.9.0=py314hca03da5_1
  - brotlicffi=1.2.0.0=py314h50f4ffc_0
  - bs4=4.14.2=py314hd3eb1b0_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - certifi=2025.11.12=py314hca03da5_0
  - cffi=2.0.0=py314h73c2a22_1
  - charset-normalizer=3.4.4=py314hca03da5_0
  - click=8.2.1=py314hca03da5_1
  - flask=3.1.2=py314hca03da5_0
  - idna=3.11=py314hca03da5_0
  - itsdangerous=2.2.0=py314hca03da5_0
  - jinja2=3.1.6=py314hca03da5_0
  - libcxx=20.1.8=hd7fd590_1
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libmpdec=4.0.0=h80987f9_0
  - libzlib=1.3.1=h5f15de7_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.2=py314h75312c3_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyh0d26453_0
  - pycparser=2.23=py314hca03da5_0
  - pysocks=1.7.1=py314hca03da5_1
  - python=3.14.2=h1858270_101_cp314
  - python_abi=3.14=2_cp314
  - readline=8.3=h0b18652_0
  - requests=2.32.5=py314hca03da5_1
  - soupsieve=2.5=py314hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - typing-extensions=4.15.0=py314hca03da5_0
  - typing_extensions=4.15.0=py314hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.6.1=py314hca03da5_0
  - werkzeug=3.1.3=py314hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
prefix: /opt/anaconda3/envs/TOC
